export type { GameState, PlayerId } from "./types";
export type { Action } from "./actions";
export {
  WILD_INDUSTRY_CARD_ID,
  WILD_LOCATION_CARD_ID,
  discardActionCard,
  refillHand,
  scout,
  type CardZones,
  type PlayableCardId,
  type WildCardId,
} from "./cards-v2";
export {
  COMMAND_SCHEMA_VERSION,
  executeCommand,
  replayCommands,
  type CommandEnvelope,
  type CommandError,
  type CommandErrorCode,
  type CommandResult,
  type ReplayResult,
} from "./commands";
export {
  deserializeGame,
  DeserializeGameError,
  serializeGame,
  type DeserializeErrorCode,
} from "./serialization";
export type { ReduceError, ReduceErrorCode, ReduceResult } from "./reduce";
export { createGame } from "./state/create";
export {
  CANAL_SETUP_SCHEMA_VERSION,
  MERCHANT_SETUP_SCHEMA_VERSION,
  RAIL_SETUP_SCHEMA_VERSION,
  createCanalSetup,
  createMerchantSetup,
  createRailSetup,
  type CanalSetupResult,
  type MerchantSetupResult,
  type MerchantSpaceSetup,
  type RailSetupResult,
  type SeatId,
  type SupportedPlayerCount,
} from "./setup-v2";
export { reduce } from "./reduce";
export { getLegalMoves, type LegalMove } from "./legal";
export {
  actionsPerTurn,
  createRoundSpendLedger,
  determineNextTurnOrder,
  nextSeat,
  recordRoundSpending,
  type LifecycleEra,
  type RoundSeatId,
  type RoundSpendLedger,
} from "./lifecycle";
export {
  INDUSTRY_INVENTORY_SCHEMA_VERSION,
  createIndustryInventory,
  developIndustryTiles,
  getLowestIndustryTileId,
  getNextBuildableIndustryTileId,
  removeBuiltIndustryTile,
  type DevelopIndustryTilesResult,
  type IndustryEra,
  type IndustryInventory,
  type IndustryInventoryError,
  type IndustryInventoryErrorCode,
  type RemoveBuiltTileResult,
} from "./player-v2";
export {
  advanceIncomeSpaces,
  applyLoanToIncome,
  canTakeLoan,
  highestSpaceForIncomeLevel,
  incomeLevelAt,
  liquidationValue,
  settleRoundIncome,
  type LiquidatableIndustry,
  type RoundIncomeSettlement,
  type RoundIncomeSettlementInput,
} from "./economy/income";
export {
  createResourceMarketState,
  purchaseFromResourceMarket,
  sellToResourceMarket,
  type ResourceMarketKind,
  type ResourceMarketPurchase,
  type ResourceMarketSale,
  type ResourceMarketState,
} from "./economy/markets";
export {
  rankFinalStandings,
  replenishMerchantBeer,
  resolveEraEnd,
  scoreBuiltIndustries,
  scoreBuiltLinks,
  scoreEraAssets,
  type BoardLinkId,
  type BoardLocationId,
  type BuiltIndustryScore,
  type BuiltLinkScore,
  type CopiedEraMerchantSpace,
  type Era,
  type EraAssetScoringResult,
  type EraEndInput,
  type EraEndResolution,
  type EraIndustryPlacement,
  type EraLinkPlacement,
  type EraMerchantSpace,
  type IndustryScoringResult,
  type LinkScoringResult,
  type PlayerStanding,
  type PlayerStandingInput,
} from "./scoring/era-transition";
export {
  takeLoan,
  type LoanActionEffect,
  type LoanActionError,
  type LoanActionErrorCode,
  type LoanActionResult,
  type LoanActionState,
} from "./actions-v2/loan";
export {
  passAction,
  type PassActionEffect,
  type PassActionError,
  type PassActionErrorCode,
  type PassActionResult,
  type PassActionState,
} from "./actions-v2/pass";
export {
  executeNetworkAction,
  planNetworkAction,
  type NetworkActionEffect,
  type NetworkActionError,
  type NetworkActionErrorCode,
  type NetworkActionPlanResult,
  type NetworkActionResult,
  type NetworkActionSelection,
  type NetworkActionState,
  type NetworkBeerEffect,
  type NetworkCoalChoice,
  type NetworkCoalEffect,
  type NetworkEra,
  type NetworkIndustryKind,
  type NetworkIndustryState,
} from "./actions-v2/network";
export {
  scoutAction,
  type ScoutActionEffect,
  type ScoutActionError,
  type ScoutActionErrorCode,
  type ScoutActionResult,
  type ScoutActionSelection,
  type ScoutActionState,
} from "./actions-v2/scout";
export {
  developAction,
  type DevelopActionEffect,
  type DevelopActionError,
  type DevelopActionErrorCode,
  type DevelopActionResult,
  type DevelopActionSelection,
  type DevelopActionState,
  type DevelopBoardIronEffect,
  type DevelopIronIndustryState,
} from "./actions-v2/develop";
export {
  sellAction,
  type SellActionEffect,
  type SellActionError,
  type SellActionErrorCode,
  type SellActionResult,
  type SellActionSelection,
  type SellActionState,
  type SellBeerEffect,
  type SellBeerSelection,
  type SellIndustryState,
  type SellMerchantBonusEffect,
  type SellMerchantSpaceState,
  type SellTileEffect,
  type SellTileSelection,
  type SellableIndustryKind,
} from "./actions-v2/sell";
export {
  executeBuildAction,
  type BuildActionEffect,
  type BuildActionError,
  type BuildActionErrorCode,
  type BuildActionResult,
  type BuildActionSelection,
  type BuildActionState,
  type BuildCoalChoice,
  type BuildEra,
  type BuildIronChoice,
  type BuildPlayerCount,
  type BuildResourceEffect,
  type BuiltIndustryState,
} from "./actions-v2/build";
export {
  GAME_STATE_V2_SCHEMA_VERSION,
  createGameV2,
  validateGameStateV2,
  type GameEraV2,
  type GameEventV2,
  type GameProgressV2,
  type GameStateV2,
  type GameStateV2ValidationError,
  type GameStateV2ValidationErrorCode,
  type GameStateV2ValidationResult,
  type PlacedIndustryStateV2,
  type PendingMerchantFreeDevelopV2,
  type PlayerStateV2,
} from "./game-v2/state";
export {
  DeserializeGameV2Error,
  deserializeGameV2,
  serializeGameV2,
  type DeserializeGameV2ErrorCode,
} from "./game-v2/serialization";
export {
  executeBuildForGameV2,
  executeDevelopForGameV2,
  executeLoanForGameV2,
  executeNetworkForGameV2,
  executePassForGameV2,
  executeScoutForGameV2,
  executeSellForGameV2,
  type AdaptedActionEffectV2,
  type FlipIncomeAwardV2,
  type GameV2ActionAdapterError,
  type GameV2ActionAdapterErrorCode,
  type GameV2ActionAdapterResult,
  type PendingActionFollowUpV2,
} from "./game-v2/action-adapters";
export {
  GAME_V2_COMMAND_SCHEMA_VERSION,
  executeGameV2Command,
  replayGameV2Commands,
  type GameV2Command,
  type GameV2CommandBoundaryErrorCode,
  type GameV2CommandEnvelope,
  type GameV2CommandError,
  type GameV2CommandOutcome,
  type GameV2CommandResult,
  type GameV2PlayerActionEffect,
  type GameV2PlayerCommand,
  type GameV2ReplayResult,
} from "./game-v2/commands";
export {
  resolveMerchantFreeDevelopV2,
  type MerchantFreeDevelopEffectV2,
  type MerchantFreeDevelopErrorV2,
  type MerchantFreeDevelopErrorCodeV2,
  type MerchantFreeDevelopResultV2,
  type MerchantFreeDevelopSelectionV2,
} from "./game-v2/merchant-free-develop";
export {
  getGameV2LegalOptions,
  type GameV2CanalNetworkOption,
  type GameV2LegalCommandKind,
  type GameV2LegalOptions,
  type GameV2LegalityDisabledReason,
  type GameV2LegalityDisabledReasonCode,
  type GameV2MerchantFreeDevelopOptions,
  type GameV2NetworkOptions,
  type GameV2PlayerActionAvailability,
  type GameV2PlayerActionKind,
  type GameV2ScoutOptions,
  type GameV2SystemCommandKind,
  type GameV2SystemCommandOptions,
} from "./game-v2/legal";
export {
  getGameV2BuildLegalOptions,
  type GameV2BuildBoardResourceSource,
  type GameV2BuildLegalDisabledReason,
  type GameV2BuildLegalDisabledReasonCode,
  type GameV2BuildLegalOptions,
  type GameV2BuildMarketResourceSource,
  type GameV2BuildResourcePlan,
  type GameV2BuildResourceSource,
  type GameV2BuildTarget,
} from "./game-v2/build-legal";
export {
  getGameV2DevelopLegalOptions,
  type GameV2DevelopBoardIronSource,
  type GameV2DevelopLegalDisabledReason,
  type GameV2DevelopLegalDisabledReasonCode,
  type GameV2DevelopLegalOptions,
  type GameV2DevelopPlan,
  type GameV2DevelopTile,
} from "./game-v2/develop-legal";
export {
  getGameV2SellLegalOptions,
  type GameV2SellBeerSummary,
  type GameV2SellBreweryBeerSummary,
  type GameV2SellIndustrySummary,
  type GameV2SellLegalDisabledReason,
  type GameV2SellLegalDisabledReasonCode,
  type GameV2SellLegalOptions,
  type GameV2SellMerchantBeerSummary,
  type GameV2SellMerchantSummary,
  type GameV2SellNextSale,
  type GameV2SellPendingFollowUp,
  type GameV2SellPlan,
  type GameV2SellProjectedSale,
} from "./game-v2/sell-legal";
export {
  getGameV2LiquidationLegalOptions,
  type GameV2LiquidationAsset,
  type GameV2LiquidationAuthorityPreview,
  type GameV2LiquidationCoverage,
  type GameV2LiquidationLegalDisabledReason,
  type GameV2LiquidationLegalDisabledReasonCode,
  type GameV2LiquidationLegalOptions,
  type GameV2LiquidationNextChoice,
  type GameV2SeatLiquidationProgress,
} from "./game-v2/liquidation-legal";
export {
  applyAcceptedActionV2,
  resolveCompletedRoundV2,
  type AcceptedActionEffectV2,
  type ApplyAcceptedActionResultV2,
  type LiquidationChoicesV2,
  type ResolveCompletedRoundResultV2,
  type TurnLifecycleError,
  type TurnLifecycleErrorCode,
} from "./game-v2/turn-lifecycle";
export {
  deriveRailSetupSeed,
  resolveGameEra,
  type EraLifecycleError,
  type EraLifecycleErrorCode,
  type EraLifecycleResult,
  type EraLifecycleSuccess,
} from "./game-v2/era-lifecycle";
export {
  RANDOM_ALGORITHM,
  createRandomState,
  nextRandom,
  nextRandomUint32,
  randomInt,
  shuffleWithState,
  type RandomState,
  type RandomStep,
} from "./util/random-state";
